blog/urls.py
from django.urls import path, include

from .views import ArticleListView, ArticleDetailView, ContactCreateView


app_name = "blog"

urlpatterns = [
    path("articles/", ArticleListView.as_view(), name="list"),
    path("articles/<str:title>", ArticleDetailView.as_view(), name="detail"),
    path('contact/', ContactCreateView.as_view(), name='contact'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

from blog import views
from blog.models import Article


handler400 = views.ArticleListView.as_view(status_code=400)
handler403 = views.ArticleListView.as_view(status_code=403)
handler404 = views.ArticleListView.as_view(status_code=404)

info_dict = {
    "queryset": Article.objects.filter(is_public=True).order_by("-created_at"),
    "date_field": "updated_at",
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path('markdownx/', include('markdownx.urls')),
    # the sitemap
    path('sitemap.xml', sitemap,
         {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.5, changefreq="weekly",)}},
         name='django.contrib.sitemaps.views.sitemap'),
    # the robots.txt
    path('robots.txt',
         cache_page(60*60*24*7)(TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
         name="robots.txt"),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.functional import cached_property
from django.core.cache import cache

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class Tag(models.Model):
    name = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255, unique=True)
    content = MarkdownxField()
    tags = models.ManyToManyField(Tag, blank=True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    counter = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/articles/"+self.title

    @cached_property
    def get_next_article(self):
        try:
            return self.get_next_by_created_at(is_public=True)
        except self.DoesNotExist as e:
            return None

    @cached_property
    def get_prev_article(self):
        try:
            return self.get_previous_by_created_at(is_public=True)
        except self.DoesNotExist as e:
            return None

    @property
    def formatted_markdown(self):
        return markdownify(self.content)

    def countup(self):
        key = "count"+str(self.id)
        unit = 10
        cache.get_or_set(key, unit, timeout=60*60*24*30)
        cache.decr(key)
        if cache.get(key) <= 0:
            self.counter += unit
            self.save(update_fields=["counter"])
            cache.incr(key, unit)
        return self.counter


class Comment(models.Model):
    name = models.CharField(max_length=30)
    article = models.ForeignKey(Article,
        related_name='comments', on_delete=models.SET_NULL, null=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    depth = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=30)
    subject = models.CharField(max_length=255, help_text="お問い合わせタイトルをご入力ください")
    mail = models.EmailField(help_text="返信先のメールアドレスをご入力ください")
    description = models.TextField(max_length=2048)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            "name",
            "description",
            "parent",
        )
        widgets = {
            "parent": forms.HiddenInput(),
        }

    def clean(self):
        cleaned_data = super().clean()
        parent = cleaned_data.get("parent", None)
        if parent and parent.depth >= 4:
            raise forms.ValidationError("これ以上、返信できません")

        return cleaned_data

blog/views.py
from logging import getLogger

from django.views.generic import CreateView, ListView, DetailView, TemplateView
from django.views.generic.edit import FormMixin
from django.urls import reverse
from django.contrib import messages
from django.urls import reverse_lazy
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Q

from .models import Article, Tag, Comment, Contact
from .forms import CommentForm


logger = getLogger(__name__)

err_msg = {
    400: "リクエストに不整合がありました",
    403: "そのページは見ることができません",
    404: "ページが見つかりませんでした",
}


class ArticleListView(ListView):
    """
    ブログ記事一覧のビューを提供する
    """
    template_name = "blog/list.html"
    context_object_name = "articles"
    model = Article
    paginate_by = 10
    http_method_names = ['get']
    status_code = None
    errors = (400, 403, 404)

    def get_queryset(self):
        q = self.request.GET.get("q", "")
        qs = Article.objects.prefetch_related("tags").filter(is_public=True).order_by("-created_at")

        if 2 < len(q):
            searched_qs = qs.filter(Q(title__contains=q) | \
                                    Q(content__contains=q) | \
                                    Q(tags__name__icontains=q))\
                            .distinct()\
                            .order_by('-created_at')
            if 0 < len(searched_qs):
                return searched_qs
            else:
                messages.error(self.request, q+"の検索結果は0件でした")
        return qs

    def get(self, request, *args, **kwargs):
        if self.status_code in self.errors:
            request.GET = request.GET.copy()
            request.GET["page"] = 1
            request.GET["q"] = ""
        res = super().get(request, *args, **kwargs)
        if self.status_code in self.errors:
            res.status_code = self.status_code
            messages.error(request, err_msg[self.status_code])
        return res

    def get_context_data(self, **kwargs):
        if self.request.GET.get("q", ""):
            kwargs["q"] = "q={}".format(self.request.GET.get("q"))
        return super().get_context_data(**kwargs)


class ArticleDetailView(FormMixin, DetailView):
    """
    ブログ記事のビューを提供する
    ただしブログ記事にはコメント投稿が備わっているため、
    `CreateView`ではなく`FormMixin`, `DetailView`を使用する
    """
    template_name = "blog/detail.html"
    context_object_name = "article"
    model = Article
    form_class = CommentForm
    slug_url_kwarg = "title"
    slug_field = "title"

    def get_queryset(self):
        return Article.objects.filter(is_public=True)

    def get_success_url(self):
        return reverse("blog:detail", kwargs={"title": self.object})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        if comment.parent:
            comment.article = comment.parent.article
            comment.depth = comment.parent.depth + 1
        comment.save()
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        res = super().get(request, *args, **kwargs)
        self.object.countup()
        return res

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["similars"] = Article.objects\
                                     .filter(tags__in=self.object.tags.all())\
                                     .exclude(id=self.object.id)\
                                     .distinct()\
                                     .order_by('?')[:3]
        context["comments"] = self.convert_comment()
        return context

    def convert_comment(self):
        """
        DBへの繰り返しアクセスを避けるため、
        コメントレコードを入れ子構造のJSONに変換する
        """
        comments = self.object.comments.order_by("-created_at").values()
        converted = []

        for comment in comments:
            comment["children"] = []

        def get_parent(_id):
            for comment in comments:
                if comment["id"] is _id:
                    return comment
            raise Article.DoesNotExist("can't find article id={}".format(_id))

        for comment in comments:
            if comment["depth"] is not 0:
                parent = get_parent(_id=comment["parent_id"])
                parent["children"].insert(0, comment)
            else:
                converted.insert(0, comment)

        return converted


class ContactCreateView(CreateView):
    template_name = "blog/contact.html"
    model = Contact
    fields = ("name", "subject", "mail", "description")
    success_url = reverse_lazy('blog:contact')

    def form_valid(self, form):
        responce = super().form_valid(form)
        subject = form.cleaned_data['subject']
        from_email = form.cleaned_data['mail']
        message = form.cleaned_data['description']
        to_email = settings.EMAIL_HOST
        try:
            send_mail(subject, message, from_email, [to_email])
            messages.success(self.request, "thanks for your contact!")
        except Exception as e:
            logger.error("failed send_mail to %s", from_email)
            logger.error("because of %s", e)
            messages.error(self.request, "sorry! failed submit because of server gone!")
        return responce

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/magula.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <link rel="stylesheet" href="{% static 'blog/main.css' %}" />
    <script src="{% static 'blog/main.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <a class="navbar-brand" href="/articles">TEST BLOG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">About</a>
            </li>
          </ul>
          <form action="{% url 'blog:list' %}" method="GET" class="form-inline my-2 my-md-0">
            <input name="q" class="form-control" type="text" placeholder="検索キーワード" minlength="3">
          </form>
        </div>
      </nav>
      <br>

      <main role="main">

        {# メッセージ表示 #}
        {% if messages %}
          {% for message in messages %}
            <div role="alert"
                 {% if message.tags == "success" %}
                   class="alert alert-primary"
                 {% else %}
                   class="alert alert-danger"
                 {% endif %}
                 >
                 {{ message }}
            </div>
          {% endfor %}
        {% endif %}

        {% block body %}{% endblock %}
        <hr>
        {% include "blog/footer.html" %}
      </main>
    </div>
  </body>
</html>

blog/templates/blog/command.html
{% extends "admin/change_list.html" %}

{% block object-tools %}
  <div>
    <form action="command/cacheclear" method="GET">
      {% csrf_token %}
      <input type="submit" value="Cache Clear">
    </form>
  </div>
  <br />
  {{ block.super }}
{% endblock %}

blog/templates/blog/comments.html
<div class="{% if comment.depth is not 0 %}comment{% endif %} card border-0" id="comment_{{ comment.id }}">
  <div class="card-body">
    <h5 class="card-title">{{ comment.name }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ comment.created_at }}</h6>
    <div class="card-text">{{ comment.description|linebreaks }}</div>
    {% if comment.depth < 4 %}
      <button type="button" class="btn btn-link" onClick="checkId(this)">返信</button>
    {% endif %}
  </div>

  {% if comment.children %}
    {% for child in comment.children %}
      {% include "blog/comments.html" with comment=child %}
    {% endfor %}
  {% endif %}
</div>

blog/templates/blog/contact.html
{% extends "blog/base.html" %}

{% block title %}
  contact
{% endblock %}

{% block body %}
  <p>お名前、お問い合わせタイトル、連絡先、問い合わせ内容を入れて"送信"をクリックしてください</p>
  <hr>
  <div>
    {% include "blog/form.html" with form=form%}
  </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block title %}
  {{ article.title }}
{% endblock %}

{% block body %}
  {# 記事の表示 #}
  <div>
    <h1>{{ article.title }}</h1>
    <p>{{ article.created_at|date:"Y年m月d日" }} viewed: {{ article.counter }}
      {% for tag in article.tags.all %}
        <a href="/articles/?q={{ tag.name }}"><span class="badge badge-info">{{ tag.name }}</span></a> 
      {% endfor %}
    </p>
    <div class="content">
      {{ article.formatted_markdown|safe }}
    </div>
  </div>

  {# 各コメントの表示 #}
  <div>
    <h2>comments</h2>
    {% for comment in comments %}
      {% include "blog/comments.html" %}
    {% endfor %}
  </div>

  {# コメントフォーム #}
  <div id="comment_form_div">
    <br>
    <h3>your comment</h3>
    {% include "blog/form.html" with form=form%}
  </div>

  {# 前後ページの表示 #}
  <div class="row">
    <div class="col-sm-6">
      <div class="card border-0">
        <div class="card-body">
          {% if article.get_prev_article %}
            <a class="card-text" href="{{ article.get_prev_article.get_absolute_url }}">&lt; {{ article.get_prev_article }}</a>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card border-0">
        <div class="card-body text-right">
          {% if article.get_next_article %}
            <a class="card-text" href="{{ article.get_next_article.get_absolute_url }}">{{ article.get_next_article }} &gt;</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {# 関係ページの表示 #}
  {% if similars %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">類似ページ</h5>
        <ol>
          {% for similar in similars %}
            <li><a href="{{ similar.get_absolute_url }}">{{ similar.title }}</a></li>
          {% endfor %}
        </ol>
      </div>
    </div>
  {% endif %}
{% endblock %}

blog/templates/blog/footer.html
{% load cache %}
{% cache 86400 footer %} {# 一日キャッシュ #}

<footer class="blog-footer">

  <div class="card-deck">
    {# 人気ページの表示 #}
    <div class="card border-0 footer-pages">
      <div class="card-body">
        <h5 class="card-title">人気ページ</h5>
        {% for popular in populars %}
          <p class="card-text"><a href="{{ popular.get_absolute_url }}">{{ popular.title }}</a></p>
        {% endfor %}
      </div>
    </div>

    {# 最新ページの表示 #}
    <div class="card border-0 footer-pages">
      <div class="card-body">
        <h5 class="card-title">最新ページ</h5>
        {% for latest in latests %}
          <p class="card-text"><a href="{{ latest.get_absolute_url }}">{{ latest.title }}</a>
        {% endfor %}
      </div>
    </div>
  </div>

  <br>
  <p class="text-center">
    <a href="#">Back to top</a>
  </p>
</footer>

{% endcache %}

blog/templates/blog/form.html
{% load widget_tweaks %}

<form method="POST">
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">送信</button>
</form>

blog/templates/blog/list.html
{% extends "blog/base.html" %}

{% block title %}
  記事一覧
{% endblock %}

{% block body %}
  {% for article in articles %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><a href="{{ article.get_absolute_url }}">{{ article }}</a></h5>
        <p>{{ article.created_at|date:"Y年m月d日" }} viewed: {{ article.counter }}
          {% if article.tags.all %}
            {% for tag in article.tags.all %}
              <a href="/articles/?q={{ tag.name }}"><span class="badge badge-info">{{ tag.name }}</span></a> 
            {% endfor %}
          {% endif %}
        </p>
      </div>
    </div>
    <br>
  {% endfor %}
  {% include "blog/pagination.html" %}
{% endblock %}

blog/templates/blog/pagination.html
<div class="mx-auto" style="width: 200px;">
  <nav aria-label="Page navigation mx-auto">
    
    {# 総ページ数が5個以内の場合はすべて表示させる #}
    {% if 1 < paginator.num_pages and paginator.num_pages <= 5 %}
      <ul class="pagination">
        {% for i in paginator.page_range %}
          <li class="page-item"><a class="page-link" href="?{{ q }}&page={{ i }}">{{ i }}</a></li>
        {% endfor %}
      </ul>

    {# 総ページ数が5個以上の場合は表示ページ数を5個にする #}
    {% elif 5 < paginator.num_pages %}
      <ul class="pagination">
        <li class="page-item"><a class="page-link" href="?{{ q }}&page=1">1</a></li>
        {% if page_obj.number < 4 %}
          {# show: 1|2|3|4 >> last #}
          <li class="page-item"><a class="page-link" href="?{{ q }}&page=2">2</a></li>
          <li class="page-item"><a class="page-link" href="?{{ q }}&page=3">3</a></li>
          <li class="page-item"><a class="page-link" href="?{{ q }}&page=4">4</a></li>
          <li class="page-item"><a class="page-link">&raquo;</a></li>
        {% elif paginator.num_pages|add:'-3' < page_obj.number %}
          {# show: 1 << last-3|last-2|last-1|last #}
          <li class="page-item"><a class="page-link">&laquo;</a></li>
          <li class="page-item"><a class="page-link" href="?{{ q }}&page={{ paginator.num_pages|add:'-3' }}">{{ paginator.num_pages|add:'-3' }}</a></li>
          <li class="page-item"><a class="page-link" href="?{{ q }}&page={{ paginator.num_pages|add:'-2' }}">{{ paginator.num_pages|add:'-2' }}</a></li>
          <li class="page-item"><a class="page-link" href="?{{ q }}&page={{ paginator.num_pages|add:'-1' }}">{{ paginator.num_pages|add:'-1' }}</a></li>
        {% else %}
          {# show: 1 << current-1|current|current+1 >> last #}
          <li class="page-item"><a class="page-link">&laquo;</a></li>
          <li class="page-item"><a class="page-link" href="?{{ q }}&page={{ page_obj.number|add:'-1' }}">{{ page_obj.number|add:'-1' }}</a></li>
          <li class="page-item"><a class="page-link" href="?{{ q }}&page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
          <li class="page-item"><a class="page-link" href="?{{ q }}&page={{ page_obj.number|add:'+1' }}">{{ page_obj.number|add:'+1' }}</a></li>
          <li class="page-item"><a class="page-link">&raquo;</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link" href="{{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
      </ul>
    </nav>
  {% endif %}
</div>